services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./crypto-monitoring-frontend
    ports:
      - "80:80"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
